//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroDeUsuario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int Id { get; set; }
        public string PrimeiroNome { get; set; }
        public string Sobrenome { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Password { get; set; }
        public bool EmailVerificado { get; set; }
        public System.Guid CodidoVerificacao { get; set; }
    }
}
